version: '3.9'
services:
  rabbitmq1:
    image: rabbitmq:3-management
    #image: rabbitmq:3.8.28-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    ports:
      - "8071:15672"
    networks:
      - cluster
    volumes:
      - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
      - $PWD/rabbitmq.conf:/etc/rabbitmq/conf.d/10-defaults.conf
      - $PWD/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
        #- $PWD/definitions.json:/etc/rabbitmq/definitions.json
    environment:
            #- RABBITMQ_ERLANG_COOKIE=zpEujZjoQutwpYsZQbWZHRQ/rCOEqT4w1A6hvkWE
      - RABBITMQ_DEFAULT_USER=mqadmin
      - RABBITMQ_DEFAULT_PASS=Admin123XX_
        #- RABBITMQ_CONFIG_FILE=/etc/rabbitmq/conf.d/rabbitmq.conf
      - CLUSTERED=true
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
 
  rabbitmq2:
    image: rabbitmq:3-management
    #image: rabbitmq:3.8.28-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    ports:
      - "8072:15672"
    networks:
      - cluster
    volumes:
      - $PWD/storage/rabbitmq2:/var/lib/rabbitmq
      - $PWD/rabbitmq.conf:/etc/rabbitmq/conf.d/10-defaults.conf
      - $PWD/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
        #- $PWD/definitions.json:/etc/rabbitmq/definitions.json
    environment:
            #- RABBITMQ_ERLANG_COOKIE=zpEujZjoQutwpYsZQbWZHRQ/rCOEqT4w1A6hvkWE
      - RABBITMQ_DEFAULT_USER=mqadmin
      - RABBITMQ_DEFAULT_PASS=Admin123XX_
        #- RABBITMQ_CONFIG_FILE=/etc/rabbitmq/conf.d/rabbitmq.conf
      - CLUSTERED=true
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
 
  rabbitmq3:
    image: rabbitmq:3-management
    #image: rabbitmq:3.8.28-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    depends_on:
      - rabbitmq2
    ports:
      - "8073:15672"
    networks:
      - cluster
    volumes:
      - $PWD/storage/rabbitmq3:/var/lib/rabbitmq
      - $PWD/rabbitmq.conf:/etc/rabbitmq/conf.d/10-defaults.conf
      - $PWD/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
        #- $PWD/definitions.json:/etc/rabbitmq/definitions.json
    environment:
            #- RABBITMQ_ERLANG_COOKIE=zpEujZjoQutwpYsZQbWZHRQ/rCOEqT4w1A6hvkWE
      - RABBITMQ_DEFAULT_USER=mqadmin
      - RABBITMQ_DEFAULT_PASS=Admin123XX_
        #- RABBITMQ_CONFIG_FILE=/etc/rabbitmq/conf.d/rabbitmq.conf
      - CLUSTERED=true
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
 
  haproxy:
    image: haproxy:1.6
    container_name: haproxy
    hostname: haproxy
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 5672:5672
      - 20000:20000
    networks:
      - cluster
    volumes:
      - $PWD/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

networks:
  cluster:
    driver: bridge
